# Generated by Django 4.2.7 on 2023-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('fristname', models.CharField(max_length=14)),
                ('lastname', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('cpassword', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=254)),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
